# Generated by Django 4.2.11 on 2024-04-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to='goods/')),
                ('introduction', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
                ('is_sale', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.IntegerField(max_length=11, unique=True)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recevie_name', models.CharField(max_length=50)),
                ('recevie_address', models.CharField(max_length=50)),
                ('recevie_tel', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='SuperCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=30)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=30)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('super_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.supercat')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.orders')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.subcat'),
        ),
        migrations.AddField(
            model_name='goods',
            name='supercat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.supercat'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.myuser')),
            ],
        ),
    ]
